name: Feature request
description: Suggest a new idea for CCCaster.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using CCCaster!

        If you are looking for support, please check out our documentation:

          - https://github.com/lurkydismal/CCCaster/wiki
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the [existing issues](https://github.com/lurkydismal/CCCaster/issues)
        required: true
      - label: I have read the [guide to filing a bug](https://github.com/lurkydismal/CCCaster/wiki/bug-reports)
        required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.

        Describe the alternative solutions you've considered. Is there a package
        on github.com/lurkydismal/CCCaster/packages that already solves this?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like CCCaster to be able to do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples

        Does this have to be provided by CCCaster directly, or can it be provided
        by a package on github.com/lurkydismal/CCCaster/packages? If so, maybe consider implementing and
        publishing such a package rather than filing an issue.
    validations:
      required: true
