blank_issues_enabled: true
contact_links:
  - name: I want help using this application
    url: https://github.com/lurkydismal/CCCaster/wiki
    about: Search your questions about how to achieve a particular effect in CCCaster or get help with using a particular API.
