name: C/C++ CI debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@84c781b557efd538dec66bde06988d81cd3138cf # v2.2.0
      with:
        platform: x86
    - name: Get APT Package Wine
      run: |
        sudo dpkg --add-architecture i386 &&
        sudo apt-get update &&
        sudo apt-get install -y wine &&
        sudo apt-get install -y wine32
      shell: bash
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        submodules: recursive
#     - name: configure
#       run: ./configure
    - name: make debug
      run: make debug
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
