# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: C/C++ CI

on:
  push:
    branches:
      - main
      - v3.1.2
    paths:
      - lib/**
      - netplay/**
      - res/**
      - scripts/**
      - targets/**
      - tests/**
      - tools/**
      - Makefile
    
  pull_request:
    branches:
      - main
      - v3.1.2

    paths:
      - lib/**
      - netplay/**
      - res/**
      - scripts/**
      - targets/**
      - tests/**
      - tools/**
      - Makefile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.build_type }} on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, logging, release]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@84c781b557efd538dec66bde06988d81cd3138cf # v2.2.0
      with:
        platform: x86

    - name: Get APT Package Wine
      run: |
        sudo dpkg --add-architecture i386 &&
        sudo apt-get update &&
        sudo apt-get install -y wine &&
        sudo apt-get install -y wine32

    - name: Checkout repository
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        submodules: recursive

#     - name: configure
#       run: ./configure

    - name: make ${{ matrix.build_type }}
      run: make ${{ matrix.build_type }}

#     - name: make check
#       run: make check

#     - name: make distcheck
#       run: make distcheck
