on:
  push:
    branches:
      - 'main'

# Declare default permissions as read only.
permissions: read-all

jobs:
  mirror_job:
    permissions:
        pull-requests: write
    runs-on: ubuntu-latest
    name: Mirror SOURCE_BRANCH_NAME branch to DESTINATION_BRANCH_NAME branch
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'main'
        dest: 'master'
